title: Hierarchical Event Descriptor (HED) Tags and related tools
description: Preparing brain imaging data for automated analysis and meta-analysis
google_analytics: UA-46460712-3
show_downloads: false
theme: jekyll-theme-cayman
organization_github_repo_url: https://github.com/hed-standard
