title: Hierarchical Event Descriptor (HED) Tags
description: Annotating brain imaging data for analysis
google_analytics: UA-46460712-3
show_downloads: false
theme: jekyll-theme-cayman
organization_github_repo_url: https://github.com/hed-standard
plugins:
  - jekyll-redirect-from
